In [7]:
def lunch(price_falafel,amount_falafel,
          price_soup,amount_soup,
          price_pita,amount_pita,):


    cost_falafel = price_falafel * amount_falafel

    cost_soup = price_soup * amount_soup

    cost_pita = price_pita * amount_pita

    total_cost = cost_falafel + cost_soup + cost_pita
    
    return total_cost
    

In [8]:
Darius = lunch(3,2,2,2,1,1)
Belle = lunch(3,1,2,1,1,4)
Amel = lunch(3,3,2,2,1,3)

total_cost = Darius + Belle + Amel
print (total_cost)

36


In [ ]:
def celsius_to_fahrenheit(celsius):
    return celsius * 9 / 5 + 32

print(celsius_to_fahrenheit(0))    # Output: 32.0
print(celsius_to_fahrenheit(100))  # Output: 212.0


In [11]:
def celsius_fahrenheit(celsius):
 fahrenheit= celsius*9/5+32

 return fahrenheit


In [28]:
fahrenheit=celsius_fahrenheit(30)
print (fahrenheit)

86.0


In [29]:
def fahrenheit_celsius(fahrenheit):
    celsius = (fahrenheit-32) * 5/9
    return celsius

In [31]:
celsius = fahrenheit_celsius(100) 
print (celsius)

37.77777777777778


In [32]:
import numpy as np

In [34]:
cost_array = np.array([300,700,100,800,200])
cost_array[0] = cost_array[0] - 100
print (cost_array)

[200 700 100 800 200]


In [35]:
cost_array = np.array([300,700,100,800,200])
cost_array[1] = cost_array[1] - 100
print (cost_array)

[300 600 100 800 200]


In [36]:
cost_array = np.array([300,700,100,800,200])
cost_array[2] = cost_array[2] - 100
print (cost_array)

[300 700   0 800 200]


In [37]:
cost_array = np.array([300,700,100,800,200])
cost_array[3] = cost_array[3] - 100
print (cost_array)

[300 700 100 700 200]


In [38]:
cost_array = np.array([300,700,100,800,200])
cost_array[4] = cost_array[4] - 100
print (cost_array)

[300 700 100 800 100]


In [39]:
cost_array = np.array([300,700,100,800,200])
cost_array[:5] = cost_array[:5] - 50
print (cost_array)

[250 650  50 750 150]


In [48]:
cost_array = [300,700,100,800,200]
for i in cost_array:
    print(i)
    
    
    print(i-50)

300
250
700
650
100
50
800
750
200
150


In [47]:
cost_array = np.array([300,700,100,800,200])
cost_array[0] = cost_array[0] - 100
print (i-50)

100
